# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: example
# Database name: pick any name
# Database host: replace "localhost" with "mysql"

version: '3'

services:

  owncloud:
    image: owncloud
    labels:
      traefik.port: "80"
      traefik.frontend.rule: "Host:127.0.0.1,localhost"
      traefik.backend: "owncloud"
    depends_on: 
      - lb

  mysql:
    image: mariadb
    volumes:
      - /home/prof/tp_asi_ensg:/etc/mysql/conf.d 
    environment:
      MYSQL_ROOT_PASSWORD: example

  lb:
    image: traefik
    ports:
      - "8080:8080"
      - "8081:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "false"
    command: --docker --docker.watch 